### ISSUE TITLE
项目运行一直卡在这，能帮忙看看吗？

### ISSUE THREAD

**Issue by Octoberr** [kerlomz/captcha_trainer#13]
感谢分享
![image](https://user-images.githubusercontent.com/17826158/56199998-8d048c80-6070-11e9-83a9-67f74ca0d1b3.png)

**Comment by kerlomz** [comment]
使用CPU，如果电脑配置一般的话，比如CPU还是低压版的话，需要很久的，训练不是一般的配置随便跑的动的，即使能跑会很慢，请理解，有条件尽量上好些的GPU

**Comment by Octoberr** [comment]
你是不是把所有的数据都读进了内存呀
