### ISSUE TITLE
准确率卡在80%很难提升是什么原因？

### ISSUE THREAD

**Issue by DogeUnicorn0096** [kerlomz/captcha_trainer#19]
![微信截图_20190527123155](https://user-images.githubusercontent.com/47493888/58395570-7abc3c00-807b-11e9-88ef-bf442ceeef65.png)
学习4位的数字英文，准确率在80左右就很难提高了，LearningRate特别低怎么解决？

**Comment by kerlomz** [comment]
准确率上不去就加样本
