### ISSUE TITLE
请问如何准备自己的训练集和测试集？

### ISSUE THREAD

**Issue by petitchamp** [kerlomz/captcha_trainer#22]
请问如何准备自己的训练集与测试集，是否需要将验证码中的每个字符单独切割出来？
还是说每张图片可以整体输入，是不是需要将每个图片用验证码字符命名？
请问能否给一个简单的例子？
谢谢

**Comment by kerlomz** [comment]
不需要切割，图片整体输入，需要将每个图片用验证码命名，标注是根据正则提取的，建议采用介绍的截图中的样式规范。比如 标注内容_时间戳/图片二进制的md5.图片格式后缀

**Comment by qqizai** [comment]
请问大佬：
1、如果将图片验证码单独每个字切割出来作为训练集，是否也行？
2、如果不切割的话，那么每张验证码大小不一样，是否能够进行训练？
