### ISSUE TITLE
大佬，没看见model_demo.yaml和config_demo.yaml两个文件啊

### ISSUE THREAD

**Issue by Funny-dot** [kerlomz/captcha_trainer#27]
大佬，没看见model_demo.yaml和config_demo.yaml两个文件啊

**Comment by kerlomz** [comment]
改版本的config_demo.yaml已经被移除，model_demo.yaml还是有的
可以参见这个分支的文档：https://github.com/kerlomz/captcha_trainer/blob/compat/README.md，待更新至一定程度将会合并至master。
