### ISSUE TITLE
后续新的训练集怎么打包进去

### ISSUE THREAD

**Issue by nq2010** [kerlomz/captcha_trainer#57]
后续新的训练集怎么打包进去，和原有的训练集合起来重新打包训练吗

**Comment by nq2010** [comment]
后续加入新的数据，准确率反而下降了

**Comment by zjy6622** [comment]
怎么加的

**Comment by kerlomz** [comment]
准确率直接和样本质量相关，你先确定下自己得样本是不是100%正确，如果不是高质量样本其实没必要增量，而且所谓得准确率下降，这个准确率指得是实际测试？还是在验证集上的表现，还有可能是你的样本没有100%标注正确，导致新加入得验证集有一部分标注其实是错误得，这时候看到的数值大小，表面上低了但可能反而在生产环境表现会更高。提问的话请注意上下文的表达，我举个例子。你的核心问题是数据和准确率发生了矛盾，那么你应该提供数据相关的信息，什么样的训练集（附带样图），样本准确率（采集方式/采集渠道），准确率（从哪里得出的准确率，是程序？还是生产环境的爬虫验证得出的？还是肉眼对比？）其次，如何加入新数据？（从GUI界面的Attach？重新打包？）
