### ISSUE TITLE
作者示例中的验证码几乎都是无法识别的

### ISSUE THREAD

**Issue by intgogo** [kerlomz/captcha_trainer#76]
![image](https://user-images.githubusercontent.com/31696329/100176040-7e4bb000-2f0a-11eb-9948-b6a78e7dc658.png)

上面的验证码，我测试了下全军覆没！

**Comment by kerlomz** [comment]
老哥，这个是训练框架，顾名思义，想要识别，需要自己动手训练，配合部署框架，才算一个完整的闭环。而文章提到的muggle是提供一个简单的模型而已，只能识别很规整的验证码，如果对高精度的通用识别感兴趣，可以测试：http://152.136.207.29:19812/preview?model_name=ENG_NUM。

**Comment by intgogo** [comment]
窝日~原来你留了一手啊~

**Comment by intgogo** [comment]
CRNN的网络架构能解决双行文字的识别啊？

**Comment by kerlomz** [comment]
不能，但是框架写了方法能顺带支持这个特殊的验证码
