### ISSUE TITLE
cannot import name 'loader' from 'tf2onnx'

### ISSUE THREAD

**Issue by songsa1** [kerlomz/captcha_trainer#77]
您好，请问可以帮我解答一下这个问题吗？这是什么情况呢？环境问题吗？
这是我本地环境
absl-py                   0.11.0
altgraph                  0.17
Appium-Python-Client      1.0.2
astor                     0.8.1
attrs                     20.2.0
Automat                   20.2.0
certifi                   2020.6.20
chardet                   3.0.4
colorama                  0.4.4
constantly                15.1.0
cssselect                 1.1.0
future                    0.18.2
gast                      0.4.0
grpcio                    1.31.0
h5py                      2.10.0
hyperlink                 20.0.1
idna                      2.10
importlib-metadata        2.0.0
incremental               17.5.0
itemadapter               0.1.1
itemloaders               1.0.3
jieba                     0.42.1
jmespath                  0.10.0
Keras-Applications        1.0.8
Keras-Preprocessing       1.1.0
Markdown                  3.3.3
mkl-fft                   1.2.0
mkl-random                1.1.1
mkl-service               2.3.0
numpy                     1.19.2
onnx                      1.8.0
opencv-python             4.4.0.46
pandas                    1.1.3
parsel                    1.6.0
pefile                    2019.4.18
Pillow                    8.0.1
pip                       20.3
Protego                   0.1.16
protobuf                  3.13.0
psycopg2                  2.8.6
pyasn1                    0.4.8
pyasn1-modules            0.2.8
PyDispatcher              2.0.5
PyHamcrest                2.0.2
pyinstaller               4.1
pyinstaller-hooks-contrib 2020.10
pymongo                   3.11.0
pyOpenSSL                 19.1.0
pyreadline                2.1
python-dateutil           2.8.1
pytz                      2020.1
pywin32-ctypes            0.2.0
PyYAML                    5.3.1
queuelib                  1.5.0
requests                  2.24.0
scipy                     1.5.2
Scrapy                    2.4.0
selenium                  3.141.0
service-identity          18.1.0
setuptools                50.3.2.post20201201
six                       1.15.0
SQLAlchemy                1.3.19
tensorboard               1.14.0
tensorflow                1.14.0
tensorflow-estimator      1.14.0
termcolor                 1.1.0
tf2onnx                   1.7.2
tqdm                      4.54.0
Twisted                   20.3.0
typing-extensions         3.7.4.3
urllib3                   1.25.10
w3lib                     1.22.0
Werkzeug                  1.0.1
wheel                     0.36.0
wincertstore              0.2
wrapt                     1.12.1
zipp                      3.4.0
zope.interface            5.1.2

**Comment by Purek** [comment]
请问楼主，最后是怎么解决的？

**Comment by Tsn-09** [comment]
> 请问楼主，最后是怎么解决的？

我把 loader 改成 tf_loader 了
